# Generated by Django 4.1 on 2022-10-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('DV', 'Developer'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
    ]
