# Generated by Django 4.1 on 2022-10-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_niche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('CB', 'Community Builders'), ('AR', 'Artist')], max_length=2, null=True),
        ),
    ]
