# Generated by Django 4.1 on 2022-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='application',
            name='under_review',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('DV', 'Developer'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('DV', 'Developer'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
    ]
