# Generated by Django 4.1 on 2022-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('CB', 'Community Builders'), ('DV', 'Developer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('RJ', 'Rejected'), ('AC', 'Accepted'), ('Wl', 'Waitlist'), ('UR', 'Under Review')], max_length=2, null=True),
        ),
    ]
