# Generated by Django 4.1 on 2022-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_remove_application_id_alter_application_niche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('DV', 'Developer'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(blank=True, choices=[('Wl', 'Waitlist'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('UR', 'Under Review')], max_length=2, null=True),
        ),
    ]
