# Generated by Django 4.1 on 2022-10-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_niche_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('RJ', 'Rejected'), ('UR', 'Under Review'), ('Wl', 'Waitlist'), ('AC', 'Accepted')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='suggestions',
            field=models.TextField(max_length=500),
        ),
    ]
