# Generated by Django 4.1 on 2022-10-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_application_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('AR', 'Artist'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('NA', 'Not Applied'), ('Wl', 'Waitlist'), ('UR', 'Under Review'), ('RJ', 'Rejected')], default='NA', max_length=2),
        ),
    ]
