# Generated by Django 4.1 on 2022-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_application_niche_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('CB', 'Community Builders'), ('DV', 'Developer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('Wl', 'Waitlist'), ('UR', 'Under Review'), ('NA', 'Not Applied')], default='NA', max_length=2),
        ),
    ]
