# Generated by Django 4.1 on 2022-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_niche_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Applied'), ('RJ', 'Rejected'), ('Wl', 'Waitlist'), ('AC', 'Accepted'), ('UR', 'Under Review')], default='NA', max_length=2),
        ),
    ]
