# Generated by Django 4.1 on 2022-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='wallet_balance',
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('PF', 'Project Founder'), ('DV', 'Developer'), ('AR', 'Artist'), ('IF', 'Influencer'), ('ME', 'Memer'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Wl', 'Waitlist'), ('UR', 'Under Review'), ('RJ', 'Rejected'), ('AC', 'Accepted'), ('NA', 'Not Applied')], default='NA', max_length=2),
        ),
    ]
