# Generated by Django 4.1 on 2022-10-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_remove_application_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('IF', 'Influencer'), ('ME', 'Memer'), ('CB', 'Community Builders'), ('AR', 'Artist'), ('PF', 'Project Founder')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Wl', 'Waitlist'), ('AC', 'Accepted'), ('NA', 'Not Applied'), ('RJ', 'Rejected'), ('UR', 'Under Review')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='wallet_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
