# Generated by Django 4.1 on 2022-10-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_application_niche_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date_submitted', 'user', 'status']},
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('AR', 'Artist'), ('CB', 'Community Builders'), ('IF', 'Influencer'), ('DV', 'Developer'), ('ME', 'Memer'), ('PF', 'Project Founder')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('UR', 'Under Review'), ('Wl', 'Waitlist'), ('NA', 'Not Applied')], default='NA', max_length=2),
        ),
    ]
