# Generated by Django 4.1 on 2022-10-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_application_options_alter_application_niche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_nft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nft_tradiing_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='trader_type',
            field=models.CharField(blank=True, choices=[('FP', 'Flipoooor'), ('HD', 'Holdoooor')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('CB', 'Community Builders'), ('PF', 'Project Founder'), ('ME', 'Memer'), ('IF', 'Influencer'), ('DV', 'Developer'), ('AR', 'Artist')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Applied'), ('UR', 'Under Review'), ('RJ', 'Rejected'), ('AC', 'Accepted'), ('Wl', 'Waitlist')], default='NA', max_length=2),
        ),
    ]
