# Generated by Django 4.1 on 2022-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_application_first_nft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('NM', 'Normie'), ('IF', 'Influencer'), ('AR', 'Artist'), ('PF', 'Project Founder'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('UR', 'Under Review'), ('NA', 'Not Applied'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('Wl', 'Waitlist')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='trader_type',
            field=models.CharField(blank=True, choices=[('HD', 'Holdoooor'), ('FP', 'Flipoooor')], max_length=2, null=True),
        ),
    ]
