# Generated by Django 4.1 on 2022-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_application_if_lost_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='application',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('CB', 'Community Builders'), ('PF', 'Project Founder'), ('IF', 'Influencer'), ('NM', 'Normie'), ('DV', 'Developer'), ('AR', 'Artist')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Applied'), ('Wl', 'Waitlist'), ('UR', 'Under Review'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='trader_type',
            field=models.CharField(blank=True, choices=[('FP', 'Flipoooor'), ('HD', 'Holdoooor')], max_length=2, null=True),
        ),
    ]
