# Generated by Django 4.1 on 2022-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_image_2_application_image_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='nft_tradiing_duration',
            new_name='nft_trading_duration',
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('NM', 'Normie'), ('AR', 'Artist'), ('IF', 'Influencer'), ('PF', 'Project Founder'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Wl', 'Waitlist'), ('NA', 'Not Applied'), ('UR', 'Under Review'), ('RJ', 'Rejected'), ('AC', 'Accepted')], default='NA', max_length=2),
        ),
    ]
