# Generated by Django 4.1 on 2022-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_rename_nft_tradiing_duration_application_nft_trading_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='problems_and_solution',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('PF', 'Project Founder'), ('NM', 'Normie'), ('DV', 'Developer'), ('IF', 'Influencer'), ('AR', 'Artist'), ('CB', 'Community Builders')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Wl', 'Waitlist'), ('NA', 'Not Applied'), ('RJ', 'Rejected'), ('AC', 'Accepted'), ('UR', 'Under Review')], default='NA', max_length=2),
        ),
    ]
