# Generated by Django 4.1 on 2022-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_application_problems_and_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='niche',
            field=models.CharField(blank=True, choices=[('CB', 'Community Builders'), ('DV', 'Developer'), ('PF', 'Project Founder'), ('IF', 'Influencer'), ('AR', 'Artist'), ('NM', 'Normie')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Applied'), ('RJ', 'Rejected'), ('UR', 'Under Review'), ('AC', 'Accepted'), ('Wl', 'Waitlist')], default='NA', max_length=2),
        ),
    ]
